# -*- coding: utf-8 -*-
"""Sample EDA Submission Template.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pLHuk5ml8brfq76USc0n0suZU4FLxCqd

# **Project Name**    - **HOTEL BOOKING ANALYSIS EDA PROJECT FOR ALMABETTER**

##### **Project Type**    - EDA/Regression/Classification/Unsupervised
##### **Contribution**    - Individual
##### **Team Member 1 -**  **SUJEET KUMAR**

# **Project Summary -**

This project is related to Hotel Booking having two hotel description ie City Hotel and Resort Hotel. In this dataset contains total rows 119390 and 32 columns. In this we divide data manipulation workflow in three category Data Collection Data cleaning and manipulation and EDA(Exploratory Data Analysis) As Further moved ie Data collections first step to find different columns which is done by coding Head(), tall). info(), describe(), columns) and some others method used for data collections, some of the columns name is updated here Le hotel is canceled, lead time,arrival_date_year_arrival_date_month,arrival_date week number,arrival_date_day_of_month stays_in_weekend_night s. As we further moved we find unique value of each columns and generate a list in tabular form and also check the dataset type of each columns find some columns not in accurate data types which correct it later done in Data cleaning part and as well as duplicates data items must be removed as we find duplicates items equal to 87396 which is dropped from dataset later.

Before visualize any data from the data set we have to do data wrangling. For that, we are checked the null value of all the columns. After checking, when we are getting a column which has more number of null values, dropped that column by using the drop method. In this way, we are dropped the 'company' column. When we are find minimal number of null values, filling the null values with necesary values as per requirement by using fillina()

Different charts are used for data visualization so that better insights and Business objective is attained.

# **GitHub Link -**

https://github.com/sujeet108

# **Problem Statement**

Have you ever wondered when the best time of year to book a hotel room is? Or the optimal length of stay in order to get the best daily rate? What if you wanted to predict whether or not a hotel was likely to receive a disproportionately high number of special requests? This hotel booking dataset can help you explore those questions! This data set contains booking information for a city hotel and a resort hotel, and includes information such as when the booking was made, length of stay, the number of adults, children, and/or babies, and the number of available parking spaces, among other things. All personally identifying information has been removed from the data. Explore and analyze the data to discover important factors that govern the bookings.

**Business Task**

Analyse the data on bookings of City Hotel and Resort Hotel to gain insights on the different factors that affect the booking. This is undertaken as an individual project.

#### **Define Your Business Objective?**

**Increment the quantity of appointments:** The fundamental goal of an inn booking task could be to expand the quantity of appointments made through the framework. This can be accomplished by giving a simple to-utilize interface, a wide determination of lodgings, and serious costs.

**Upgrade client experience:** Another significant goal could be to give an incredible client experience, which incorporates an easy to understand point of interaction, quick and effective booking process, simple crossing out and change strategies, and fantastic client care.

**Smooth out tasks:** An inn booking undertaking can likewise expect to smooth out tasks and make them more effective. This should be possible via robotizing cycles, for example, booking affirmation, installment handling, and room tasks.

**Create income:** The task can expect to produce income by offering extra administrations, for example, air terminal exchanges, visits, and exercises, and by cooperating with different organizations to offer packaged bundles.

**Fabricate brand notoriety:** At last, the undertaking can expect to construct areas of strength for a standing by offering great support, keeping up with straightforwardness and genuineness with clients, and effectively captivating with them through virtual entertainment and different channels.

# **General Guidelines** : -

1.   Well-structured, formatted, and commented code is required. 
2.   Exception Handling, Production Grade Code & Deployment Ready Code will be a plus. Those students will be awarded some additional credits. 
     
     The additional credits will have advantages over other students during Star Student selection.
       
             [ Note: - Deployment Ready Code is defined as, the whole .ipynb notebook should be executable in one go
                       without a single error logged. ]

3.   Each and every logic should have proper comments.
4. You may add as many number of charts you want. Make Sure for each and every chart the following format should be answered.
        

```
# Chart visualization code
```
            

*   Why did you pick the specific chart?
*   What is/are the insight(s) found from the chart?
* Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

5. You have to create at least 20 logical & meaningful charts having important insights.


[ Hints : - Do the Vizualization in  a structured way while following "UBM" Rule. 

U - Univariate Analysis,

B - Bivariate Analysis (Numerical - Categorical, Numerical - Numerical, Categorical - Categorical)

M - Multivariate Analysis
 ]

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries
"""

# Commented out IPython magic to ensure Python compatibility.
# Import Libraries
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
# %matplotlib inline
from datetime import datetime
import seaborn as sns
import ast

from google.colab import drive
drive.mount('/content/drive')

"""### Dataset Loading"""

# Load Dataset
database = "/content/Hotel Bookings.csv"
hotal_booking_df =pd.read_csv(database)

"""### Dataset First View"""

# Dataset First Look
hotal_booking_df

"""### Dataset Rows & Columns count"""

# Dataset Rows & Columns count
print(hotal_booking_df.index)
print('/n')
print(hotal_booking_df.columns)

"""### Dataset Information"""

# Dataset Info
hotal_booking_df.info()

"""#### Duplicate Values"""

# Dataset Duplicate Value Count
hotal_booking_df.drop_duplicates(inplace = True)

# total rows = 119390, Duplicate Rows = 31994
uni_num_of_rows = hotal_booking_df.shape[0]

uni_num_of_rows # now unique rows = 87396

"""#### Missing Values/Null Values"""

# Missing Values/Null Values Count
null_values = hotal_booking_df.isnull()  == True
hotal_booking_df.fillna(np.nan, inplace = True)

hotal_booking_df # we replace all the null value as Nan.

# Visualizing the missing values
miss_values = hotal_booking_df.isnull().sum().sort_values(ascending=False)
miss_values # We have check the count of null value in individual columns

"""### What did you know about your dataset?

This data set contains a single file which compares various booking information between two hotels: a city hotel and a resort hotel. Includes information such as when the booking was made, length of stay, the number of adults, children, and/or babies, and the number of available parking spaces, among other things. The dataset contains a total of 119390 rows and 32 columns.Dataset Contains duplicated items i.e 31944 which is removed later .In this dataset we find data types of every columns i.e (Int, float,string) and observe that some columns data types is not accurate and remove later. We find unique value of every columns it means what actual values in every columns.

## ***2. Understanding Your Variables***
"""

# Dataset Columns
df_column = hotal_booking_df.columns
df_column

# Dataset Describe
hotal_booking_df.describe()

"""### Variables Description

**The columns and the data it represents are listed below:**

1. **hotel:** Name of the hotel (Resort Hotel or City Hotel)
2. **is_canceled:** If the booking was canceled (1) or not (0)
3. **lead time:** Number of days before the actual arrival of the guests
4. **arrival_date_year:** Year of arrival date
5. **arrival_date_month:** Month of month arrival date
6.**arrival_date_week_number:** Week number of year for arrival date
7. **arrival_date_day_of_month:** Day of arrival date
8. **stays_in_weekend_nights:** Number of weekend nights (Saturday or Sunday) spent at the hotel by the guests.
9. **stays_in_week_nights:** Number of weeknights (Monday to Friday) spent at the hotel by the guests.
10. **adults:** Number of adults among guests
11. **children:** Number of children among guests
12. **babies:** Number of babies among guests
13. **meal:** Type of meal booked
14. **country:** Country of guests
15. **market segment:** Designation of market segment
16. **distribution_channel:** Name of booking distribution channel
17. **is_repeated_guest:** If the booking was from a repeated guest (1) or not (0)
18. **previous_cancellations:** Number of previous bookings that were cancelled by the customer prior to the current booking
19. **previous_bookings_not_canceled:** Number of previous bookings not cancelled by the customer prior to the current booking
20. **reserved_room_type:** Code of room type reserved
21. **assigned_room_type:** Code of room type assigned
22. **booking changes:** Number of changes/amendments made to the booking
23. **deposit_type:** Type of the deposit made by the guest
24. **agent:** ID of travel agent who made the booking
25. **company:** ID of the company that made the booking
26. **days_in_waiting list:** Number of days the booking was in the waiting list
27. **customer_type:** Type of customer, assuming one of four categories
28. **adr :** Average Daily Rate, as defined by dividing the sum of all lodging transactions by the total number of staying nights
29. **required_car_parking spaces:** Number of car parking spaces required by the customer
30. **total_of_special_requests:** Number of special requests made by the customer
31. **reservation_status:** Reservation status (Canceled, Check-Out or No-Show)
32. **reservation_status_date:** Date at which the last reservation status was updated

### Check Unique Values for each variable.
"""

# Check Unique Values for each variable.
print(hotal_booking_df.apply(lambda col: col.unique())) # we have describes unique values in all indivisual column.

"""## 3. ***Data Wrangling***

### Data Wrangling Code
"""

# Write your code to make your dataset analysis ready.
miss_values[:4]

#lets check, what is the percentage of null value in each column, starting from company
percentage_company_null = miss_values[0] / uni_num_of_rows*100
percentage_company_null

# It is better to drop the column 'company' altogether since the number of missing values is extremely high.
hotal_booking_df.drop(['company'], axis=1, inplace=True)

# now let's check for agent
percentage_company_null = miss_values[1] / uni_num_of_rows*100
percentage_company_null

# As we have seen, there is minimum nul value in agent. lets fill these value by taking mode of the all values
hotal_booking_df['agent'].fillna(value = 0, inplace = True)
hotal_booking_df['agent'].isnull().sum() # we re-check that column has no null value

# check the percentage null value in country col

percentage_company_null = miss_values[2] / uni_num_of_rows*100
percentage_company_null

# We have less null values in country col, so we will replace null from 'other' as country name.
hotal_booking_df['country'].fillna(value = 'other' , inplace = True)
hotal_booking_df['country'].isnull().sum() # we re-check that column has no null value

# Check the percentage null value in children col
percentage_company_null = miss_values[3] / uni_num_of_rows*100
percentage_company_null

# We have less null values in country col, so we will replace null from 0 as country name.
hotal_booking_df['children'].fillna(value = 0, inplace = True)
hotal_booking_df['children'].isnull().sum() # we re-check that column has no null value

# let's check weather database having any other null value

hotal_booking_df.isnull().sum() # As we have seen, no column has any null value

# Showing the info of the data to check datatype
hotal_booking_df.info()

# We have seen that childer & agent column as datatype as float whereas it contains only it contains only int value, lets chenge datatype as 'int64'
hotal_booking_df[['children', 'agent']] = hotal_booking_df[['children', 'agent']].astype('int64')

# total stay in nights
hotal_booking_df['total_stay_in_nights'] = hotal_booking_df ['stays_in_week_nights'] + hotal_booking_df ['stays_in_weekend_nights']
hotal_booking_df['total_stay_in_nights'] # we have created a col for total stays in nights by adding week nights by adding week night & weekend nights stay column

# we have created a col for revanue using total stay * adr
hotal_booking_df['revenue'] = hotal_booking_df ['total_stay_in_nights'] + hotal_booking_df ['adr']
hotal_booking_df['revenue']

# Also, for information, we will add a column with total guest coming for each booking
hotal_booking_df['total_guest'] = hotal_booking_df ['adults'] + hotal_booking_df ['children'] + hotal_booking_df['babies']
hotal_booking_df['total_guest'].sum()

# for understanding, from col 'is_canceled' : we will replace the value from (0,1) to not_canceled, is canceled.
hotal_booking_df['is_canceled'] = hotal_booking_df ['is_canceled'].replace([0,1], ['not canceled', 'is_canceled'])
hotal_booking_df['is_canceled']

# Same for 'is_repeated_guest' col
hotal_booking_df['is_repeated_guest'] = hotal_booking_df ['is_repeated_guest'].replace([0,1], ['not repeated', 'repeated'])
hotal_booking_df['is_repeated_guest']

# Now we will check over all revenue hotal wise
hotal_wise_total_revenue = hotal_booking_df.groupby('hotel')['revenue'].sum()
hotal_wise_total_revenue

"""### What all manipulations have you done and insights you found?

**We have done few manipulations in the Data.**

**----Addition of columns----**

We have seen that there are few columns required in Data to analysis purpose which can be evaluated from the given columns.

a) **Total Guests:** This columns will help us to evaluate the volumes of total guest and revenue as well. We get this value by adding total no. of Adults, Children & babies.

b) **Revenue:** We find revenue by multiplying adr & total guest. This column will use to analyse the profit and growth of each hotel.

**----Delete of columns----**

a)**company:** As we have seen that this columns has almost Null data, so we have delete this column as this will not make any impact in the
analysis.

**----Replace of Values in columns...**.

a)**is_canceled, is_not_canceled & is repeated guest:** We have seen, that these columns contains only 0,1 as values which represent the status of booing cancellation. We replace these values (0,1) from 'Canceled' & 'Not canceled. In the same way for column is repeated guest, we replace 0,1 from 'Repeated' & 'Not repeated". Now this values will help to make better understanding while visulization.

**----Changes in data type of values in columns----**

a) **Agent & Children:** We checked that these columns contains float values, which is not making any sense in data as this values represent the count of guest & ID of agent. So we have changed the data type of these columns from 'float' to 'integer'.

**----Removed is null values & duplicate entries----**

a)Before visualize any data from the data set we have to do data wrangling. For that, we have checked the null value in all the columns. After checking, when we are getting a column which has more number of null values, dropped that column by using the 'drop' method. In this way, we are dropped the 'company column. When we are find minimal number of null values, filling the null values with necesary values as per requirement by using fillina()

b) in the same, we have checked if there is any duplicacy in data & we found that there are few rows have duplicate data. So we have removed those row from data set by using drop duplicates() method.

**In this way, we have removed unneccesary data & make our data clean and ready to analyse.**

## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1
"""

# let's create a function which will give us bar chart of data respective with a col.
import pandas as pd
import matplotlib.pyplot as plt

def get_count_from_column_bar(df, column_label):
    df_grpd = df[column_label].value_counts()
    df_grpd = pd.DataFrame({'index': df_grpd.index, 'count': df_grpd.values})
    return df_grpd

def plot_bar_chart_from_column(df, column_label, title):
    df_grpd = get_count_from_column_bar(df, column_label)
    fig, ax = plt.subplots(figsize=(14,6))
    c = ['g', 'r', 'b', 'c', 'y']
    ax.bar(df_grpd['index'], df_grpd['count'], width=0.4, align='edge', edgecolor='black', linewidth=4, color=c, linestyle=':', alpha=0.8)
    plt.title(title, bbox={'facecolor':'0.8', 'pad':3})
    plt.legend()
    plt.ylabel('Count')
    plt.xticks(rotation=15) # use to format the label of x-axis
    plt.xlabel(column_label)
    plt.show()

# Chart - 1 visualization code
def get_count_from_column(df, column_label):
  df_grpd = df[column_label].value_counts()
  df_grpd = pd.DataFrame({'index' : df_grpd.index, 'count' : df_grpd.values})
  return df_grpd

# plot a pie chart from group data
def plot_pie_chart_from_column(df, column_label, t1, exp):
  df_grpd = get_count_from_column(df, column_label)
  fig, ax = plt.subplots(figsize = (14,9))
  ax.pie(df_grpd.loc[:, 'count'], labels=df_grpd.loc[:, 'index'], autopct='%1.2f%%', startangle=90,shadow=True, labeldistance = 1, explode = exp)
  plt.title(t1, bbox={'facecolor' : '0.8', 'pad':3})
  ax.axis('equal')
  plt.legend()
  plt.show()

unique_hotels = hotal_booking_df['hotel'].nunique()
expl = [0.05] * unique_hotels
plot_pie_chart_from_column(hotal_booking_df, 'hotel', 'Booking percentage by Hotel', expl)

"""##### 1. Why did you pick the specific chart?

**To present the data that in which hotel more booking have been done.**

##### 2. What is/are the insight(s) found from the chart?

**Here, we found that the booking number is Higher in City Hotel which is 61.12% than Resort Hotel which is 38.87%. Hence we can say that City hotel has more consumption**

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

**Yes, for both Hotels, this data making some positive business impact:-**

**City Hotel :- Provided more services to attract more guest to increase more revenue.**

**Resort Hotel :- Find solution to attract guest and find what city hotel did to attract guest.**

#### Chart - 2
"""

# Chart - 2 visualization code
exp4 = [0,0.2]
plot_pie_chart_from_column(hotal_booking_df, 'is_canceled', 'Cancellation volume of hotal', exp4)

"""##### 1. Why did you pick the specific chart?

**in this chart, we presented the cancellation rate of the hotals booking**

##### 2. What is/are the insight(s) found from the chart?

**Here, we found that overall more than 25% of booking got cancelled**

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

**Here, we can see, that more than 27% booking getting cancelled.**

**Solution: We can check the reason of cancellation of a booking & need to get this sort on business level**

#### Chart - 3
"""

# Chart - 3 visualization code
exp2 = [0.2,0,0,0,0,0,0,0,0,0,0,0.1]
plot_pie_chart_from_column(hotal_booking_df, 'arrival_date_month', 'Month-wise booking', exp2)

"""##### 1. Why did you pick the specific chart?

**To show the percentage share of booking in each month,on overall level**

##### 2. What is/are the insight(s) found from the chart?

**The above percentage shows month May, July and Aug are the highest booking months due to holiday season. Recommending aggressive advertisement to lure more and more customers.**

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

**Yes with incresed volumn of visitors will help hotal to manage revenue in down time, will also help employee satisfaction and retention.**

#### Chart - 4
"""

# Chart - 4 visualization code
exp3 = [0,0.2]
plot_pie_chart_from_column(hotal_booking_df, 'is_repeated_guest', 'Guest repeating status', exp3)

"""##### 1. Why did you pick the specific chart?

**To show the percentage share of repeated & non-repeated guests.**

##### 2. What is/are the insight(s) found from the chart?

**Here, we can see that the number of repeated guests is very less as compared to overall guests**

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

**We can give alluring offers to non-repetitive customers during Off seasons to enhance revenue**

#### Chart - 5
"""

# Chart - 5 visualization code
plot_bar_chart_from_column(hotal_booking_df, 'distribution_channel', 'Distribution Channel Volume')

"""##### 1. Why did you pick the specific chart?

**The following chart represent maximum volume of booking done through which channel to represnt the numbers in descending order we chose bar graph**

##### 2. What is/are the insight(s) found from the chart?

**As clearly seen TA/TO(Tour of Agent & Tour of operator) is highest, recommending to continue booking through TA/TO**

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

**Yes this shows positive business impact.**

**Higher the number of TA/TO will help to increase the revenue generation of Hotel.**

#### Chart - 6
"""

# Chart - 6 visualization code
plot_bar_chart_from_column(hotal_booking_df, 'assigned_room_type', 'Assigment of room by type')

"""##### 1. Why did you pick the specific chart?

**To show distribution by volume, which room is alotted.**

##### 2. What is/are the insight(s) found from the chart?

**This chart shows room type'A' is most prefered by guest.**

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

**Yes, positive impact because 'A','D','E' is more prefered by guest due to better services offered in room type.**

#### Chart - 7
"""

# Chart - 7 visualization code
guest_month_wise = pd.DataFrame(hotal_booking_df[['arrival_date_month','total_guest']])
guest_month_wise_df = guest_month_wise.groupby(['arrival_date_month'])['total_guest'].sum()
guest_month_wise_df.sort_values(ascending=False, inplace=True)

hotal_booking_df['total_guest']

market_segment_df = pd.DataFrame(hotal_booking_df['market_segment'])
market_segment_data = market_segment_df.groupby('market_segment')['market_segment'].count()
market_segment_data.sort_values(ascending=False, inplace=True)

plt.figure(figsize=(15,6))
market_segment_data.plot(kind='bar', color=['g', 'r', 'c', 'b', 'y', 'black', 'brown'], fontsize=20, legend=True)
plt.title('Market Segment Distribution', fontsize=25)
plt.xlabel('Market Segment', fontsize=20)
plt.ylabel('Count', fontsize=20)
plt.show()

"""##### 1. Why did you pick the specific chart?

**In this chart, we have seen market segment by which hotal has booked.**

##### 2. What is/are the insight(s) found from the chart?

**Online TA has been used most frequently to book hotal by the guest.**

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

**Yes, It is creating positive bussiness impact that guests are using online TA market segment as most prefered to book hotals.**

#### Chart - 8
"""

# Chart - 8 visualization code
guest_country_wise = pd.DataFrame(hotal_booking_df[['country', 'total_guest']])
guest_country_wise_df = guest_country_wise.groupby(['country'])['total_guest'].sum()
guest_country_wise_df.sort_values(ascending=False, inplace=True)
top_10_country_by_guest = guest_country_wise_df.head(10)

plt.figure(figsize=(12,6))
sns.barplot(x=top_10_country_by_guest.index, y=top_10_country_by_guest).set(title='Top 10 Countries by Guest')
print("\n\nPRT = Portugal\nGBR = Great Britain & Northern Ireland\nFRA = France\nESP = Spain\nDEU = Germany\nITA = Itely\nIRL = Ireland\nBRA = Brazil\nBEL = Belgium\nNLD = Netherland")

"""##### 1. Why did you pick the specific chart?

**We have seen that mostly from which country Guests is coming**

**Chart is showing for top 10 country**

##### 2. What is/are the insight(s) found from the chart?

**As we can see, the maximum guest is coming from Portugal**

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

**We can do more advertising & can provide attractive offers to Portugal guests to enhance the customer volume.**

#### Chart - 9
"""

# Chart - 9 visualization code
order = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']

ordered_hotel_df = hotal_booking_df[hotal_booking_df['is_canceled'] == 'not canceled']['arrival_date_month'].value_counts().reindex(order)

plt.subplots(figsize=(10, 6))
ticks = np.arange(0, 20000, 1500)
labels = ["{}".format(i//1000) for i in ticks]
plt.yticks(ticks, labels)
plt.xticks(rotation=60)
for xy in zip(ordered_hotel_df.index, ordered_hotel_df.values):
    plt.annotate(text="{}".format(xy[1]//1), xy=xy, textcoords="data")
plt.plot(ordered_hotel_df.index, ordered_hotel_df.values, linewidth=4, color='r', linestyle='dotted', marker='+', markersize=20, alpha=1)
plt.xlabel("Months", fontdict={'fontsize': 12, 'fontweight': 5, 'color': 'Brown'})
plt.ylabel("Counts", fontdict={'fontsize': 12, 'fontweight': 5, 'color': 'Brown'})
plt.title("Month-wise Booking", fontdict={'fontsize': 20, 'fontweight': 5, 'color': "Green"})
plt.show()

plt.figure(figsize=(8, 5))

hotel_wise_revenue = hotal_booking_df.groupby('hotel')['revenue'].sum()

ax = hotel_wise_revenue.plot(kind='bar', color=('b', 'y'))

plt.xlabel("Hotel", fontdict={'fontsize': 12, 'fontweight': 5, 'color': 'Brown'})
plt.ylabel("Total Revenue", fontdict={'fontsize': 12, 'fontweight': 5, 'color': 'Brown'})
plt.title("Total Revenue", fontdict={'fontsize': 12, 'fontweight': 5, 'color': 'r'})

average_adr = hotal_booking_df.groupby("hotel")['adr'].mean()

plt.subplots(figsize=(14, 6))

average_adr.plot(kind = 'barh', color = ('brown', 'orange'))

plt.xlabel("Average ADR", fontdict={'fontsize': 12, 'fontweight': 5, 'color': 'Brown'})
plt.ylabel("Hotel Name", fontdict={'fontsize': 12, 'fontweight': 5, 'color': 'Brown'})
plt.title("Average ADR of Hotels", fontdict={'fontsize': 20, 'fontweight': 5, 'color': "Green"})

"""##### 1. Why did you pick the specific chart?

**To specify the average ADR for both hotels.**

##### 2. What is/are the insight(s) found from the chart?

**As we can see the average ADR of City hotel is higher than Resort hotel, so the profit and revenue will be higher for city hotel.**

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

**Here, we can do more advertising for City hotel to get more customer, which result higher profit.**

#### Chart - 10
"""

# Chart - 10 visualization code
plt.figure(figsize=(12,10), dpi=100)

hotel_wise_meal = hotal_booking_df.groupby(['hotel', 'meal'])['meal'].count().unstack()

hotel_wise_meal.plot(kind='bar', figsize=(12,8))

"""##### 1. Why did you pick the specific chart?

**To show the meal preferance of the guest hotel-wise.**

##### 2. What is/are the insight(s) found from the chart?

**As we can see, BB (Bed & breakfast) meal is most prefered by guests in both the hotels. So Hotel can give more delisious dishes in this meal to get customer repeat & attaract new customer.**

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

**Resort hotel need to improve their menu for getting more customers.**

#### Chart - 11
"""

# Chart - 11 visualization code
plt.figure(figsize=(12,6))
sns.scatterplot(y='total_stay_in_nights', x='adr', data=hotal_booking_df[hotal_booking_df['adr'] < 1088])
plt.title("Scatter Plot of ADR vs Total Stay in Nights")
plt.xlabel("ADR")
plt.ylabel("Total Stay in Nights")
plt.show()

"""##### 1. Why did you pick the specific chart?

**To show comparision & affect of total stay days vs ADR**

##### 2. What is/are the insight(s) found from the chart?

**Here, we found that if guest's stay days is getting decreased, ADR is getting high**

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

**We have to improve facilities and need to more advertising for getting a more customers for long stay.**

#### Chart - 12
"""

# Chart - 12 visualization code
hotal_booking_df.hist(figsize=(24,18))
plt.show()

"""##### 1. Why did you pick the specific chart?

**To understanding the data in clear way with proper insights, have used the histogram here.ltr is used to summarize discrete or continuoud data that are measured on an interval scale. It is often used to illustrate the major feautures of the distribution of the data in convenient form. It is also usefuk when dealing with large data sets (greater than 100 observation).It can help detect any unusual observation (outliers)or any gaps in the data. Thus we have used the histogram plot to analysis the variable distribution over the whole dataset whether it's symmetric or not**

##### 2. What is/are the insight(s) found from the chart?

**Some insights found the chart as follows:**

**We can see that the maximum guest came in the year 2016 Maximum arrival week number is 30. Maximum arrival happens in the last of the month. Maximum guests comes with no children. There is very less requrement of car parking spaces.**

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

**Are there any insights that lead to negative growth? Justify with specific reason.**

**Are there any insights that lead to negative growth? Justify with specific reason.**

**Just histogram cannot define buisness impact.it's done just to see the distribution of the column data over the dataset**

#### Chart - 13
"""

# Chart - 13 visualization code
explode = [0.1] * 5
labels = hotal_booking_df["required_car_parking_spaces"].value_counts().index

hotal_booking_df["required_car_parking_spaces"].value_counts().plot.pie(
    explode=explode, 
    autopct='%1.1f%%', 
    shadow=False, 
    figsize=(16, 14), 
    fontsize=15, 
    labels=labels
)

plt.title('% Distribution of Required Car Parking Space', fontsize=15)
plt.legend(bbox_to_anchor=(1.0, 1.0), loc='upper left', labels=labels)

plt.show()

"""##### 1. Why did you pick the specific chart?

**We have used pie chart here because it gives the output in more understanding manner as we can clearly see the different two colors reflecting the demand of car parking space by guest**

##### 2. What is/are the insight(s) found from the chart?

**The pie chart shows 91.6 guest doesn't required car parking space only 8.39% guests required only 1 parking space**

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

**Yes the insights gained from here definitely help the hotels to provide better service it can be said that hotel need to work on car parking space as only 1 car parking space required by 8,3% of guest so its better to have limited car parking space and use the remaining space for other importan work So it is better to focus on other areas to increase the quality of hotel rather than car parking space.**

#### Chart - 14 - Correlation Heatmap
"""

# Correlation Heatmap visualization code
plt.figure(figsize=(20,10))
plt.title('Correlation of the columns', fontsize=15)

corr_matrix = hotal_booking_df.corr()

sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', center=0)

plt.show()

"""##### 1. Why did you pick the specific chart?

**To understand the relationsip between different numerical values.**

##### 2. What is/are the insight(s) found from the chart?

**Highest corelation value between axis is 95% positive & lowest corelation value between the axis is -51% negative.**

#### Chart - 15 - Pair Plot
"""

# Pair Plot visualization code
plt.figure(figsize=(400,500))
pd.plotting.scatter_matrix(hotal_booking_df, figsize= (10,10))
plt.show()

"""##### 1. Why did you pick the specific chart?

**Pair plot is used to understand the best set of features to explain a relationship between two variables or to form the**

##### 2. What is/are the insight(s) found from the chart?

**We have found the relationship of its repeated guest with different types of columns So, generally this chart effects the realtionship of a paricular column with a other column.**

## **5. Solution to Business Objective**

#### What do you suggest the client to achieve Business Objective ? 
Explain Briefly.

**Business objective attained as follows:**

1. For hotel business to flourish few things which we need to consider is high revenue generation, customers satisfaction and employee retention.

2. We are able achieve the same by showing the client which are the months which are high in revenue generation by pie chart distribution

3. Increasing the revenue achieved by bar chart distribution of which typre room are most reserved and what are the months likely for visitors

4. So for these the client can be well prepare in advance so that minimum grievances would be faced by clients in long run and would help in further enhancement of their hospitality.

5. Outliers like higher the visitor then adr has reduced drastically was shown in scattered plot so in off season client can engage with offices for bulk booking this will aslo help extra revenue generation

6. We are able to show the trend of arrivals of visitor at client locations through which client engaged visitos well advance for there entertainment and leisure activities

7. We where also able to co relate the values showing the max and min percentage between them so that the percenytage lying those numbers can be enhanced by verious medium.

# **Conclusion**

1. City Hotel seems to be more preferred among travellers and it also generates more revenue & profit

2. Most number of bookings are made in July and August as compared rest of the months

3. Room Type A is the most preferred room type among travellers.

4. Most number of bookings are made from Portugal & Great Britain.

5. Most of the guest stays for 1-4 days in the hotels

6. City Hotel retains more number of guests.

7. Around one-fourth of the total bookings gets cancelled. More cancellations are from City Hotel

8. New guest tends to cancel bookings more than repeated customers.

9. Lead time, number of days in waiting list or assignation of reserved room to customer does not affect cancellation of bookings.

10. Corporate has the most percentage of repeated guests while TA/TO has the least whereas in the case of cancelled bookings TA/TO has the most percentage while Corporate has the least.

11. The length of the stay decreases as ADR increases probably to reduce the cos

### ***Hurrah! You have successfully completed your EDA Capstone Project !!!***
"""